name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda automaticamente toda meia-noite
  workflow_dispatch: # Permite que você rode manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Garante permissão para salvar a imagem
    
    steps:
      - name: Generate snake gif
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23800080
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
